### ISSUE TITLE
패치 설치 상태에서 설정 제거 후 패치 설치시 패치 설치 버튼 표시됨

### ISSUE THREAD

**Issue by Laeng** [SCKorea/Shatagon#7]
재연 방법
1. 패치 설치 후 게임 실행
2. 설정 파일 제거
3. 패치 설치 후 `처음` 버튼 눌러 메인 화면 진입
4. `게임 시작` 버튼 대신 `패치 설치` 버튼 표시 됨을 확인 가능

**Comment by marona42** [comment]
기동시 설정파일 읽기 시도 후 설정이 없으면 default 로드 및 디렉토리에 코어모듈 파일 감지 필요

**Comment by Laeng** [comment]
setting.json 정보와 user.cfg 정보, global.ini 파일 존재 여부가 미스매치 될 때 재설치 되도록 변경했습니다.
